
# Exercício 1 – Vendas por loja

Crie, no seu notebook, um DataFrame de vendas com os dados abaixo (pode ser via dicionário ou lista de dicionários):

Colunas:

id_venda (1, 2, 3, 4)

loja ("Centro", "Shopping", "Centro", "Online")

produto ("Teclado", "Mouse", "Monitor", "Headset")

data ("2024-10-01", "2024-10-01", "2024-10-02", "2024-10-03")

valor (200.0, 150.0, 900.0, 300.0)

In [3]:
import pandas as pd 

dados = {
    "id_venda": [1,2,3,4],
    "loja":["Centro","Shopping","Centro","Online"],
    "produto":["Teclado","Mouse","Monitor","Headset"],
    "data":["2024-10-01", "2024-10-01", "2024-10-02", "2024-10-03"],
    "valor":[200.0, 150.0, 900.0, 300.0]
}

df = pd.DataFrame(dados)

Tarefas:

Defina id_venda como índice usando set_index.

Converta data para datetime com pd.to_datetime.

Renomeie a coluna valor para valor_venda com rename.

Mostre o DataFrame final e verifique os tipos (dtypes).

In [5]:
df_index_alterado = df.set_index("id_venda")
df_index_alterado

              loja  produto        data  valor
id_venda
1           Centro  Teclado  2024-10-01  200.0
2         Shopping    Mouse  2024-10-01  150.0
3           Centro  Monitor  2024-10-02  900.0
4           Online  Headset  2024-10-03  300.0

In [12]:
df_index_alterado["datas"] = pd.to_datetime(df_index_alterado["data"])
df_index_alterado.dtypes

loja                  str
produto               str
data                  str
valor             float64
datas      datetime64[us]
dtype: object

In [18]:
df_renomeado = df_index_alterado.rename(columns={"valor": "valor_venda"})
df_renomeado

              loja  produto        data  valor_venda      datas
id_venda
1           Centro  Teclado  2024-10-01        200.0 2024-10-01
2         Shopping    Mouse  2024-10-01        150.0 2024-10-01
3           Centro  Monitor  2024-10-02        900.0 2024-10-02
4           Online  Headset  2024-10-03        300.0 2024-10-03

In [19]:
df_renomeado.dtypes

loja                      str
produto                   str
data                      str
valor_venda           float64
datas          datetime64[us]
dtype: object

# Exercício 2 – Índice por cidade

Crie um DataFrame com informações de cidades:

Colunas:

cidade: "Juiz de Fora", "São Paulo", "Rio de Janeiro", "Belo Horizonte"

estado: "MG", "SP", "RJ", "MG"

populacao: 573285, 12300000, 6718903, 2521564

In [22]:
cidades = { 
"cidade":["Juiz de Fora", "São Paulo", "Rio de Janeiro", "Belo Horizonte"],
"estado":["MG", "SP", "RJ", "MG"],
"populacao": [573285, 12300000, 6718903, 2521564]
}

df_cidades = pd.DataFrame(cidades)
df_cidades

           cidade estado  populacao
0    Juiz de Fora     MG     573285
1       São Paulo     SP   12300000
2  Rio de Janeiro     RJ    6718903
3  Belo Horizonte     MG    2521564

Tarefas:

Use set_index para criar um índice multi-nível com estado e cidade.

Dica: df.set_index(["estado", "cidade"])

Mostre o DataFrame com esse índice multi-nível.

Use reset_index para voltar ao índice padrão.

Em um comentário no código, explique um cenário em que um índice multi-nível faz sentido, por exemplo:

Analisar dados por (estado, cidade),

(ano, mês),

(loja, setor).

In [26]:
df_index_alterado = df_cidades.set_index(["estado","cidade"])
df_index_alterado

# O indice multinivel faz sentido para analisar dados por estado e cidade como no caso abaixo

                       populacao
estado cidade
MG     Juiz de Fora       573285
SP     São Paulo        12300000
RJ     Rio de Janeiro    6718903
MG     Belo Horizonte    2521564

In [25]:
df_resetado = df_index_alterado.reset_index()
df_resetado

  estado          cidade  populacao
0     MG    Juiz de Fora     573285
1     SP       São Paulo   12300000
2     RJ  Rio de Janeiro    6718903
3     MG  Belo Horizonte    2521564