# 3 – Exploração Avançada dos Dados (EDA com Pandas)

## 1. Objetivos da aula
Ao final desta aula, você será capaz de:

* Explorar um DataFrame de forma estruturada, não só dando head() e torcendo.
* Usar:
    * `describe()` para estatísticas descritivas.
    * `value_counts`, `unique`, `nunique` para entender categorias.
    * `min`, `max`, `quantile` para entender a distribuição.
* Ter uma noção inicial de outliers (valores muito fora da curva).
* Escrever pequenos “mini-relatórios” com insights a partir dos números.

Essa é a aula em que o aluno começa a fazer perguntas inteligentes para os dados.

## 2. O que é EDA (Exploratory Data Analysis)?
EDA = Exploratory Data Analysis = Análise Exploratória de Dados. Antes de treinar modelo, fazer dashboard ou tomar decisão, você precisa:

* Ver como os dados estão distribuídos.
* Entender a ordem de grandeza dos valores.
* Descobrir se tem dados faltando, categorias estranhas, outliers bizarros.
* Ter uma “sensação” do dataset: o que é normal, o que é raro, o que parece errado.

Pandas é perfeito para esse trabalho de detetive inicial.

## 3. Dataset exemplo: Loja de Roupas
Vamos trabalhar com um exemplo de uma loja de roupas.

In [1]:
import pandas as pd

dados = {
    "produto": [
        "Camiseta Básica", "Calça Jeans", "Vestido Floral", "Jaqueta Couro",
        "Camiseta Básica", "Calça Jeans", "Shorts Jeans", "Moletom", "Moletom", "Vestido Floral"
    ],
    "categoria": [
        "Camisetas", "Calças", "Vestidos", "Jaquetas",
        "Camisetas", "Calças", "Shorts", "Moletons", "Moletons", "Vestidos"
    ],
    "preco": [49.90, 159.90, 199.90, 399.90, 59.90, 149.90, 89.90, 129.90, 139.90, 219.90],
    "quantidade_vendida": [120, 80, 45, 10, 150, 70, 60, 90, 110, 30]
}

df_loja = pd.DataFrame(dados)
df_loja

           produto  categoria  preco  quantidade_vendida
0  Camiseta Básica  Camisetas   49.9                 120
1      Calça Jeans     Calças  159.9                  80
2   Vestido Floral   Vestidos  199.9                  45
3    Jaqueta Couro   Jaquetas  399.9                  10
4  Camiseta Básica  Camisetas   59.9                 150
5      Calça Jeans     Calças  149.9                  70
6     Shorts Jeans     Shorts   89.9                  60
7          Moletom   Moletons  129.9                  90
8          Moletom   Moletons  139.9                 110
9   Vestido Floral   Vestidos  219.9                  30

Dá uma olhada rápida:

In [2]:
df_loja.head()

           produto  categoria  preco  quantidade_vendida
0  Camiseta Básica  Camisetas   49.9                 120
1      Calça Jeans     Calças  159.9                  80
2   Vestido Floral   Vestidos  199.9                  45
3    Jaqueta Couro   Jaquetas  399.9                  10
4  Camiseta Básica  Camisetas   59.9                 150

In [3]:
df_loja.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   produto             10 non-null     str
 1   categoria           10 non-null     str
 2   preco               10 non-null     float64
 3   quantidade_vendida  10 non-null     int64
dtypes: float64(1), int64(1), str(2)
memory usage: 452.0 bytes

## 4. `describe()` – Estatísticas descritivas

### 4.1. Apenas colunas numéricas (padrão)

In [4]:
df_loja.describe()

            preco  quantidade_vendida
count   10.000000           10.000000
mean   159.900000           76.500000
std    100.664459           42.820686
min     49.900000           10.000000
25%     99.900000           48.750000
50%    144.900000           75.000000
75%    189.900000          105.000000
max    399.900000          150.000000

Você deve ver algo assim (para preco e quantidade_vendida):

* **count** – quantos valores existem
* **mean** – média
* **std** – desvio padrão
* **min** – valor mínimo
* **25%, 50%, 75%** – quartis (Q1, mediana, Q3)
* **max** – valor máximo

Isso já te dá uma visão geral do que é “normal” nesses dados.

### 4.2. Incluindo colunas não numéricas (include="all")

In [5]:
df_loja.describe(include="all")

                produto  categoria       preco  quantidade_vendida
count                10         10   10.000000           10.000000
unique                6          6         NaN                 NaN
top     Camiseta Básica  Camisetas         NaN                 NaN
freq                  2          2         NaN                 NaN
mean                NaN        NaN  159.900000           76.500000
std                 NaN        NaN  100.664459           42.820686
min                 NaN        NaN   49.900000           10.000000
25%                 NaN        NaN   99.900000           48.750000
50%                 NaN        NaN  144.900000           75.000000
75%                 NaN        NaN  189.900000          105.000000
max                 NaN        NaN  399.900000          150.000000

Aqui você pode ver para colunas de texto:

* **unique** – quantidade de valores únicos.
* **top** – valor mais frequente.
* **freq** – frequência desse valor.

É como se fosse um pequeno resumo de cada coluna.

## 5. `value_counts`, `unique`, `nunique` 
Para entender categorias (tipo categoria, produto, cidade etc.), essas funções são essenciais.

### 5.1. Valores únicos (unique e nunique)

In [6]:
df_loja["categoria"].unique()

<StringArray>
['Camisetas', 'Calças', 'Vestidos', 'Jaquetas', 'Shorts', 'Moletons']
Length: 6, dtype: str

In [7]:
df_loja["categoria"].nunique()

6

`unique()` → lista de categorias diferentes.
`nunique()` → número de categorias.

### 5.2. Frequência de cada categoria (value_counts)

In [8]:
df_loja["categoria"].value_counts()

categoria
Camisetas    2
Calças       2
Vestidos     2
Moletons     2
Jaquetas     1
Shorts       1
Name: count, dtype: int64

Você vai ver algo como:

```
Camisetas    X
Calças       Y
...
```

Também dá pra usar `normalize=True` para ver proporções:

In [9]:
df_loja["categoria"].value_counts(normalize=True)

categoria
Camisetas    0.2
Calças       0.2
Vestidos     0.2
Moletons     0.2
Jaquetas     0.1
Shorts       0.1
Name: proportion, dtype: float64

Isso mostra a fração de vendas que cada categoria representa.

## 6. Quartis, mínimos e máximos (`min`, `max`, `quantile`)
Além do `describe()`, às vezes queremos olhar especificamente para certos pontos.

### 6.1. Mínimo, máximo e média

In [10]:
df_loja["preco"].min()

np.float64(49.9)

In [11]:
df_loja["preco"].max()

np.float64(399.9)

In [12]:
df_loja["preco"].mean()

np.float64(159.9)

### 6.2. Quartis com quantile

In [13]:
q1 = df_loja["preco"].quantile(0.25)
q2 = df_loja["preco"].quantile(0.50)  # mediana
q3 = df_loja["preco"].quantile(0.75)

q1, q2, q3

(np.float64(99.9), np.float64(144.9), np.float64(189.9))

Isso ajuda a entender:

* Até quanto estão os 25% mais baratos (q1).
* “Preço típico” (mediana, q2).
* Faixa dos 25% mais caros (q3 até o máximo).

## 7. Identificação inicial de outliers (intuitivamente)
Outlier = valor muito fora da curva. Exemplos:

* Uma jaqueta de R$ 10.000,00 no meio de produtos de R$ 50 a R$ 400.
* Uma quantidade vendida de 10.000 unidades onde o normal é 50–200.

### 7.1. Inspeção visual com describe

In [29]:
df_loja["preco"].describe()

count     10.000000
mean     159.900000
std      100.664459
min       49.900000
25%       99.900000
50%      144.900000
75%      189.900000
max      399.900000
Name: preco, dtype: float64

Se o max for muuuuito maior que o 75%, é sinal de que tem algo estranho (ou um produto premium, ou erro).

<a id="secao-outliers"></a>

### 7.2. IQR (Intervalo Interquartílico) – versão simples
IQR = Q3 - Q1 Uma regra comum:

* Valores menores que Q1 - 1.5*IQR → possíveis outliers inferiores.
* Valores maiores que Q3 + 1.5*IQR → possíveis outliers superiores.

Exemplo:

In [27]:
precos = df_loja["preco"]

q1 = precos.quantile(0.25)
q3 = precos.quantile(0.75)
iqr = q3 - q1

limite_inferior = q1 - 1.5 * iqr
limite_superior = q3 + 1.5 * iqr

limite_inferior, limite_superior

(np.float64(-35.099999999999994), np.float64(324.9))

Depois, você pode ver quais produtos fogem muito:

In [ ]:
outliers = df_loja[
    (df_loja["preco"] < limite_inferior) | (df_loja["preco"] > limite_superior)]
outliers

         produto categoria  preco  quantidade_vendida
3  Jaqueta Couro  Jaquetas  399.9                  10

Na nossa tabelinha pequena é provável que não haja outliers bizarros, mas é assim que você faria num dataset real. ⚠️ Importante: Outlier não é “erro” automaticamente. Pode ser:

* Um produto premium.
* Uma promoção muito louca.
* Um erro de digitação (R$ 10.000 em vez de R$ 100).

EDA serve pra levantar suspeitas, não pra tirar conclusões definitivas sozinho.

## 8. Pequeno “profiling” manual do dataset
Vamos fazer um mini check-list de EDA com o df_loja:

### 8.1. Quantas linhas e colunas?

In [17]:
df_loja.shape

(10, 4)

### 8.2. Tipos de cada coluna

In [18]:
df_loja.dtypes

produto                   str
categoria                 str
preco                 float64
quantidade_vendida      int64
dtype: object

### 8.3. Valores nulos?

In [19]:
df_loja.isna().sum()

produto               0
categoria             0
preco                 0
quantidade_vendida    0
dtype: int64

### 8.4. Estatísticas das colunas numéricas

In [20]:
df_loja.describe()

            preco  quantidade_vendida
count   10.000000           10.000000
mean   159.900000           76.500000
std    100.664459           42.820686
min     49.900000           10.000000
25%     99.900000           48.750000
50%    144.900000           75.000000
75%    189.900000          105.000000
max    399.900000          150.000000

### 8.5. Distribuição das categorias

In [21]:
df_loja["categoria"].value_counts()

categoria
Camisetas    2
Calças       2
Vestidos     2
Moletons     2
Jaquetas     1
Shorts       1
Name: count, dtype: int64

A partir disso, você já consegue escrever algo como:

> “Temos 10 registros de produtos, divididos em X categorias. Os preços variam de R$ 49,90 a R$ 399,90, com preço médio de ~R$ xxx. A categoria mais vendida em quantidade é X, mas a de maior preço é Y.”

Esse hábito de falar o que você está vendo é o começo da habilidade de storytelling com dados.

## 9. Segundo dataset exemplo: Plataforma de Cursos Online
Vamos agora para um contexto de plataforma de cursos.

In [22]:
dados_cursos = {
    "curso": [
        "Python Básico", "Python Avançado", "Data Science com Python",
        "Introdução ao SQL", "Machine Learning", "Excel para Dados",
        "Power BI Essencial", "Estatística Aplicada"
    ],
    "area": [
        "Programação", "Programação", "Data Science",
        "Banco de Dados", "Data Science", "Ferramentas",
        "Ferramentas", "Estatística"
    ],
    "avaliacao": [4.5, 4.7, 4.8, 4.2, 4.6, 4.3, 4.4, 4.1],
    "horas": [12, 20, 25, 10, 30, 8, 15, 18],
    "qtde_alunos": [1200, 800, 950, 600, 700, 1100, 900, 500]
}

df_cursos = pd.DataFrame(dados_cursos)
df_cursos

                     curso            area  avaliacao  horas  qtde_alunos
0            Python Básico     Programação        4.5     12         1200
1          Python Avançado     Programação        4.7     20          800
2  Data Science com Python    Data Science        4.8     25          950
3        Introdução ao SQL  Banco de Dados        4.2     10          600
4         Machine Learning    Data Science        4.6     30          700
5         Excel para Dados     Ferramentas        4.3      8         1100
6       Power BI Essencial     Ferramentas        4.4     15          900
7     Estatística Aplicada     Estatística        4.1     18          500

### 9.1. Distribuição por área

In [23]:
df_cursos["area"].value_counts()

area
Programação       2
Data Science      2
Ferramentas       2
Banco de Dados    1
Estatística       1
Name: count, dtype: int64

Isso te mostra quais áreas têm mais cursos.

### 9.2. Estatísticas das colunas numéricas

In [24]:
df_cursos[["avaliacao", "horas", "qtde_alunos"]].describe()

       avaliacao     horas  qtde_alunos
count   8.000000   8.00000     8.000000
mean    4.450000  17.25000   843.750000
std     0.244949   7.57345   241.183836
min     4.100000   8.00000   500.000000
25%     4.275000  11.50000   675.000000
50%     4.450000  16.50000   850.000000
75%     4.625000  21.25000   987.500000
max     4.800000  30.00000  1200.000000

Perguntas que você pode responder:

* Qual a avaliação média dos cursos?
* Qual curso é mais longo?
* Quantos alunos em média cada curso tem?

### 9.3. Quem tem mais alunos? Quem é melhor avaliado?

In [25]:
df_cursos.sort_values("qtde_alunos", ascending=False).head(1)

           curso         area  avaliacao  horas  qtde_alunos
0  Python Básico  Programação        4.5     12         1200

In [26]:
df_cursos.sort_values("avaliacao", ascending=False).head(1)

                     curso          area  avaliacao  horas  qtde_alunos
2  Data Science com Python  Data Science        4.8     25          950

Com isso você consegue escrever:

> “O curso mais popular em número de alunos é X, com Y alunos. O curso com melhor avaliação é Z, com nota W.”

Ou ainda:

> “A área de Data Science tem cursos bem avaliados e com boa carga horária, sendo uma área relevante para investir.”

Esse tipo de frase é exatamente o que você leva pra um relatório ou apresentação.

## 10. Resumo da aula
Nesta aula, você aprendeu a:

* Usar `describe()` (numérico e com `include="all"`).
* Usar `unique`, `nunique`, `value_counts` para entender colunas categóricas.
* Obter `min`, `max`, `quantile` para entender a distribuição de uma variável.
* Ter uma primeira noção de outliers usando IQR.
* Fazer um mini-profiling manual de um DataFrame:
    * `shape`, `dtypes`, `isna().sum()`, `describe()`, `value_counts()`.

A partir de agora, toda vez que você pegar um dataset novo, você já tem um roteiro de exploração inicial.