# Exercícios: Limpeza de Dados – Parte 1 (Nulos, Duplicados, Tipos)

## Exercício 1 – Cadastro de clientes com buracos
Crie um DataFrame `df_clientes` com as colunas:
* `id_cliente` 
* `nome` 
* `idade` 
* `renda` 
* `cidade` 

Inclua intencionalmente:
* Alguns valores nulos em `idade` e `renda`.
* Pelo menos uma linha duplicada.
* Uma ou duas linhas com `cidade` igual a `None` ou vazia.

In [ ]:
import pandas as pd
import numpy as np

dados_clientes = {
    "id_cliente": [1, 2, 3, 4, 4, 5, 6],
    "nome": ["Ana", "Bruno", "Carla", "Daniel", "Daniel", "Eduarda", "Felipe"],
    "idade": [25, np.nan, 32, 40, 40, np.nan, 28],
    "renda": [3000.0, 7000.0, np.nan, 12000.0, 12000.0, 5000.0, np.nan],
    "cidade": ["Juiz de Fora", "São Paulo", None, "Rio de Janeiro", "Rio de Janeiro", "", "Belo Horizonte"]
}
df_clientes = pd.DataFrame(dados_clientes)
df_clientes

### Tarefa 1.1
Use `df_clientes.isna().sum()` para contar os nulos em cada coluna.

### Tarefa 1.2
Remova linhas totalmente duplicadas (todas as colunas iguais) usando `drop_duplicates` e salve o resultado em `df_clientes_limpo`.

### Tarefa 1.3
Preencha:
* `renda` nula com a média da coluna `renda`.
* `cidade` nula com o texto "Desconhecida".

### Tarefa 1.4
Verifique novamente os nulos com `isna().sum()`.

### Tarefa 1.5
Em texto, responda:
* Quantas linhas foram removidas por serem duplicadas?
* Após o preenchimento, ainda restam valores nulos em alguma coluna?

> *Sua resposta aqui*

## Exercício 2 – Datas e tipos quebrados
Crie um DataFrame `df_pedidos` com as colunas:
* `id_pedido` (alguns como texto, ex.: "1", "2", "3")
* `data_pedido` (com formatos ligeiramente diferentes, ex.: "2024-10-01", "2024/10/02", "10-03-2024")
* `valor` (como texto, com vírgula e ponto misturados, e pelo menos um valor não numérico, ex.: "abc")

In [3]:
import pandas as pd

dados_pedidos = {
    "id_pedido": ["1", "2", "3", "4", "5"],
    "data_pedido": ["2024-10-01", "2024/10/02", "10-03-2024", "2024-10-04", "data_errada"],
    "valor": ["200.50", "350,00", "150.00", "abc", "500.00"]
}
df_pedidos = pd.DataFrame(dados_pedidos)
df_pedidos

  id_pedido  data_pedido   valor
0         1   2024-10-01  200.50
1         2   2024/10/02  350,00
2         3   10-03-2024  150.00
3         4   2024-10-04     abc
4         5  data_errada  500.00

### Tarefa 2.1
Use `df_pedidos.dtypes` para ver os tipos atuais.

In [5]:
df_pedidos.dtypes

id_pedido      str
data_pedido    str
valor          str
dtype: object

### Tarefa 2.2
Converta `data_pedido` para datetime usando `pd.to_datetime` com `errors="coerce"`.
* Verifique se algum valor virou `NaT`.

In [12]:
df_pedidos["data_pedido"] = pd.to_datetime(df_pedidos["data_pedido"], errors="coerce")
df_pedidos

  id_pedido data_pedido   valor
0         1  2024-10-01  200.50
1         2         NaT  350,00
2         3         NaT  150.00
3         4  2024-10-04     abc
4         5         NaT  500.00

### Tarefa 2.3
Crie uma coluna `valor_limpo` substituindo vírgula por ponto em `valor` (use `str.replace(",", ".", regex=False)`).

In [17]:
df_pedidos['valor_limpo'] = df_pedidos['valor'].str.replace(",",".", regex=False)
df_pedidos

  id_pedido data_pedido   valor valor_limpo
0         1  2024-10-01  200.50      200.50
1         2         NaT  350,00      350.00
2         3         NaT  150.00      150.00
3         4  2024-10-04     abc         abc
4         5         NaT  500.00      500.00

### Tarefa 2.4
Converta `valor_limpo` para numérico em uma nova coluna `valor_num` usando `pd.to_numeric` com `errors="coerce"`.

In [30]:
df_pedidos['valor_num']=pd.to_numeric(df_pedidos['valor_limpo'],errors="coerce")
df_pedidos

  id_pedido data_pedido   valor valor_limpo  valor_num
0         1  2024-10-01  200.50      200.50      200.5
1         2         NaT  350,00      350.00      350.0
2         3         NaT  150.00      150.00      150.0
3         4  2024-10-04     abc         abc        NaN
4         5         NaT  500.00      500.00      500.0

### Tarefa 2.5
Remova as linhas em que `valor_num` ficou nulo, salvando o resultado em `df_pedidos_validos`.

In [ ]:
df_pedidos_validos = df_pedidos.dropna(subset=["valor_num"]).copy()
df_pedidos_validos

  id_pedido data_pedido   valor valor_limpo  valor_num
0         1  2024-10-01  200.50      200.50      200.5
1         2         NaT  350,00      350.00      350.0
2         3         NaT  150.00      150.00      150.0
4         5         NaT  500.00      500.00      500.0

### Tarefa 2.6 (Opcional)
Converta `id_pedido` para inteiro com `astype("int64")`, se possível.

In [32]:
df_pedidos_validos['id_pedido'] = df_pedidos_validos['id_pedido'].astype("int64")
df_pedidos_validos

   id_pedido data_pedido   valor valor_limpo  valor_num
0          1  2024-10-01  200.50      200.50      200.5
1          2         NaT  350,00      350.00      350.0
2          3         NaT  150.00      150.00      150.0
4          5         NaT  500.00      500.00      500.0

### Tarefa 2.7
Em texto, explique:
* Quantas linhas foram descartadas por terem valor inválido?
* Há alguma data que não foi convertida corretamente? Se sim, qual?

In [33]:
linhas_descartadas = len(df_pedidos) - len(df_pedidos_validos)
linhas_descartadas

1