# Cópia vs “view” e o SettingWithCopyWarning

# O problema clássico

Quando você filtra um DataFrame, às vezes o pandas não tem certeza se você está mexendo na visão (view) do original ou em uma cópia independente.

In [2]:
import pandas as pd 

datas = pd.date_range(start="2024-10-01", periods=10, freq="D")

dados_vendas = {
    "data": datas,
    "loja": ["Centro", "Centro", "Shopping", "Shopping", "Centro",
             "Centro", "Shopping", "Centro", "Shopping", "Centro"],
    "faturamento": [150, 200, 400, 500, 800, 200, 200, 100, 480, 301]
}
df_vendas = pd.DataFrame(dados_vendas)
df_vendas

        data      loja  faturamento
0 2024-10-01    Centro          150
1 2024-10-02    Centro          200
2 2024-10-03  Shopping          400
3 2024-10-04  Shopping          500
4 2024-10-05    Centro          800
5 2024-10-06    Centro          200
6 2024-10-07  Shopping          200
7 2024-10-08    Centro          100
8 2024-10-09  Shopping          480
9 2024-10-10    Centro          301

Existem duas boas práticas:
# Usar .loc no DataFrame original

In [11]:
df_vendas.loc[df_vendas["faturamento"] > 300, "valor_com_desconto"] = df_vendas["faturamento"] * 0.9
df_vendas

        data      loja  faturamento  valor_com_desconto
0 2024-10-01    Centro          150                 NaN
1 2024-10-02    Centro          200                 NaN
2 2024-10-03  Shopping          400               360.0
3 2024-10-04  Shopping          500               450.0
4 2024-10-05    Centro          800               720.0
5 2024-10-06    Centro          200                 NaN
6 2024-10-07  Shopping          200                 NaN
7 2024-10-08    Centro          100                 NaN
8 2024-10-09  Shopping          480               432.0
9 2024-10-10    Centro          301               270.9

In [14]:
df_vendas.fillna(value="Sem desconto")

        data      loja  faturamento valor_com_desconto
0 2024-10-01    Centro          150       Sem desconto
1 2024-10-02    Centro          200       Sem desconto
2 2024-10-03  Shopping          400              360.0
3 2024-10-04  Shopping          500              450.0
4 2024-10-05    Centro          800              720.0
5 2024-10-06    Centro          200       Sem desconto
6 2024-10-07  Shopping          200       Sem desconto
7 2024-10-08    Centro          100       Sem desconto
8 2024-10-09  Shopping          480              432.0
9 2024-10-10    Centro          301              270.9

# Criar uma cópia explícita
Se você realmente quer trabalhar em um DataFrame separado:

Ao usar .copy(), você diz explicitamente:

“Sim, eu quero um DataFrame independente.”

In [17]:
df_caros = df_vendas[df_vendas["faturamento"] > 300].copy()

df_caros["valor_com_desconto"] = df_caros["faturamento"] * 0.9

df_caros

        data      loja  faturamento  valor_com_desconto
2 2024-10-03  Shopping          400               360.0
3 2024-10-04  Shopping          500               450.0
4 2024-10-05    Centro          800               720.0
8 2024-10-09  Shopping          480               432.0
9 2024-10-10    Centro          301               270.9