In [1]:
import pandas as pd

dados_vendas = {

    "id_venda": [1, 2, 3, 4, 5, 6, 7, 8],
    
    "cidade": [
        "Juiz de Fora", "Juiz de Fora", "São Paulo", "São Paulo",
        "Rio de Janeiro", "Rio de Janeiro", "Juiz de Fora", "São Paulo"
    ],

    "canal_venda": [
        "Online", "Loja Física", "Online", "Marketplace",
        "Loja Física", "Online", "Online", "Loja Física"
    ],


    "valor": [200.0, 350.0, 500.0, 300.0, 800.0, 150.0, 400.0, 250.0]
}

df_vendas = pd.DataFrame(dados_vendas)
df_vendas

   id_venda          cidade  canal_venda  valor
0         1    Juiz de Fora       Online  200.0
1         2    Juiz de Fora  Loja Física  350.0
2         3       São Paulo       Online  500.0
3         4       São Paulo  Marketplace  300.0
4         5  Rio de Janeiro  Loja Física  800.0
5         6  Rio de Janeiro       Online  150.0
6         7    Juiz de Fora       Online  400.0
7         8       São Paulo  Loja Física  250.0

### Usando agg para múltiplas métricas

Você pode renomear as colunas:

In [3]:
resumo_cidade = df_vendas.groupby("cidade")["valor"].agg(
    total_faturado="sum",
    ticket_medio="mean",
    qtde_vendas="count"
)
resumo_cidade

                total_faturado  ticket_medio  qtde_vendas
cidade
Juiz de Fora             950.0    316.666667            3
Rio de Janeiro           950.0    475.000000            2
São Paulo               1050.0    350.000000            3

Se quiser tirar o índice e transformar cidade em coluna de novo:

In [4]:
resumo_cidade = resumo_cidade.reset_index()
resumo_cidade

           cidade  total_faturado  ticket_medio  qtde_vendas
0    Juiz de Fora           950.0    316.666667            3
1  Rio de Janeiro           950.0    475.000000            2
2       São Paulo          1050.0    350.000000            3

### Agrupando múltiplas colunas com `agg` 
Imagine que queremos um resumo por cidade com soma de valor, número de vendas (`id_venda`) e a venda máxima. Você pode passar um dicionário para o `agg`:

In [ ]:
resumo = df_vendas.groupby("cidade").agg({
    "valor": ["sum", "mean", "max"],
    "id_venda": "count"
})

resumo

                 valor                    id_venda
                   sum        mean    max    count
cidade
Juiz de Fora     950.0  316.666667  400.0        3
Rio de Janeiro   950.0  475.000000  800.0        2
São Paulo       1050.0  350.000000  500.0        3