### Notas por disciplina
Agora vamos para um contexto de notas de alunos por disciplina:

In [3]:
import pandas as pd
dados_notas = {
    "aluno": [
        "Ana", "Ana", "Ana",
        "Bruno", "Bruno", "Carla", "Carla", "Daniel", "Eduarda", "Eduarda"
    ],
    "disciplina": [
        "Matemática", "Português", "História",
        "Matemática", "História", "Matemática", "Português", "História", "Matemática", "Português"
    ],
    "nota": [8.0, 7.5, 9.0, 6.0, 7.0, 9.5, 8.0, 5.5, 7.0, 8.5]
}

df_notas = pd.DataFrame(dados_notas)
df_notas

     aluno  disciplina  nota
0      Ana  Matemática   8.0
1      Ana   Português   7.5
2      Ana    História   9.0
3    Bruno  Matemática   6.0
4    Bruno    História   7.0
5    Carla  Matemática   9.5
6    Carla   Português   8.0
7   Daniel    História   5.5
8  Eduarda  Matemática   7.0
9  Eduarda   Português   8.5

###  Média de notas por disciplina

In [4]:
media_por_disciplina = df_notas.groupby("disciplina")["nota"].mean()
media_por_disciplina

disciplina
História      7.166667
Matemática    7.625000
Português     8.000000
Name: nota, dtype: float64

Se quiser como DataFrame, com coluna renomeada:

In [5]:
media_por_disciplina = (
    df_notas.groupby("disciplina", as_index=False)["nota"]
            .mean()
            .rename(columns={"nota": "media_nota"})
)
media_por_disciplina

   disciplina  media_nota
0    História    7.166667
1  Matemática    7.625000
2   Português    8.000000

### Média de notas por aluno

In [8]:
media_por_aluno = (
    df_notas.groupby("aluno", as_index=False)["nota"]
            .mean()
            .rename(columns={"nota": "media_nota"})
)
media_por_aluno

     aluno  media_nota
0      Ana    8.166667
1    Bruno    6.500000
2    Carla    8.750000
3   Daniel    5.500000
4  Eduarda    7.750000

Podemos ordenar para ver o ranking:

In [7]:
media_por_aluno.sort_values("media_nota", ascending=False)

     aluno  media_nota
2    Carla    8.750000
0      Ana    8.166667
4  Eduarda    7.750000
1    Bruno    6.500000
3   Daniel    5.500000

###  Resumo geral por disciplina (média, min, max)