<a href="https://colab.research.google.com/github/lucasat2/Jornada_python/blob/main/introducao_pandas/Limpeza__de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd


# GERANDO VALORES NULOS
data = {
'A': [1,2,np.nan,4,5],
'B':[np.nan,2,3,4,5],
'C': [1,2,3,np.nan,np.nan]
}

In [5]:
df = pd.DataFrame(data)

In [6]:
df

     A    B    C
0  1.0  NaN  1.0
1  2.0  2.0  2.0
2  NaN  3.0  3.0
3  4.0  4.0  NaN
4  5.0  5.0  NaN

In [3]:
df.isna()  #tem valores nulos?

       A      B      C
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False   True
4  False  False   True

In [4]:
df.dropna() # remove valores nulos das linhas e exibe só as linhas completas

     A    B    C
1  2.0  2.0  2.0

In [7]:
df.dropna(axis = 1) # remove colunas inteiras com pelo menos 1 valor nulo(prejudicial)
# Todas as colunas foram removidas pois tem pelo menos 1 valor nulo em todas.

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [8]:
df.fillna("N") # substitui valores nulos por algo

     A    B    C
0  1.0    N  1.0
1  2.0  2.0  2.0
2    N  3.0  3.0
3  4.0  4.0    N
4  5.0  5.0    N