<a href="https://colab.research.google.com/github/lucasat2/Jornada_python/blob/main/introducao_pandas/operacoes_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

# CRIAR UMA SERIE COM NUMEROS ALEATORIOS

data_series = np.random.normal(0, 1 ,100)
data_series2 = np.random.normal(0,1,100)

frame = {
'coluna1': data_series,
'coluna2': data_series2

}
df = pd.DataFrame(frame)

df

     coluna1   coluna2
0   1.050571  0.288274
1   0.662079  0.334281
2  -0.595614 -0.648139
3   1.115918  1.065824
4  -1.455355  0.305695
..       ...       ...
95 -1.164057  1.079703
96  1.345990 -0.338182
97  0.699204 -1.261378
98  0.057885 -0.900014
99  0.503968  0.597121

[100 rows x 2 columns]

In [2]:
df.describe()

          coluna1     coluna2
count  100.000000  100.000000
mean     0.135733   -0.090308
std      0.952594    0.900443
min     -1.761345   -2.561536
25%     -0.530896   -0.729427
50%      0.007708    0.022880
75%      0.815407    0.507023
max      2.454732    1.869965

In [3]:
df.head() # 5 primeiros registros

    coluna1   coluna2
0  1.050571  0.288274
1  0.662079  0.334281
2 -0.595614 -0.648139
3  1.115918  1.065824
4 -1.455355  0.305695

In [4]:
df.tail()  # 5 ultimos registros

     coluna1   coluna2
95 -1.164057  1.079703
96  1.345990 -0.338182
97  0.699204 -1.261378
98  0.057885 -0.900014
99  0.503968  0.597121

In [5]:
df.sort_values(by='coluna1') # classificar valores

     coluna1   coluna2
59 -1.761345  0.409049
80 -1.738748 -2.274745
79 -1.534326 -1.008229
4  -1.455355  0.305695
34 -1.290980  0.421823
..       ...       ...
38  1.684984 -0.592714
31  1.776091  0.487393
86  2.150563  0.266829
48  2.187941 -0.229618
22  2.454732 -0.212701

[100 rows x 2 columns]

In [11]:
df['Total'] = df['coluna1'] + df['coluna2'] # criar nova coluna com soma de outras 2

In [12]:
df

     coluna1   coluna2     Total
0   1.050571  0.288274  1.338844
1   0.662079  0.334281  0.996360
2  -0.595614 -0.648139 -1.243753
3   1.115918  1.065824  2.181742
4  -1.455355  0.305695 -1.149660
..       ...       ...       ...
95 -1.164057  1.079703 -0.084354
96  1.345990 -0.338182  1.007808
97  0.699204 -1.261378 -0.562174
98  0.057885 -0.900014 -0.842129
99  0.503968  0.597121  1.101089

[100 rows x 3 columns]

In [13]:
df.drop(columns='Total', inplace= True) # Apagar uma coluna

In [14]:
df

     coluna1   coluna2
0   1.050571  0.288274
1   0.662079  0.334281
2  -0.595614 -0.648139
3   1.115918  1.065824
4  -1.455355  0.305695
..       ...       ...
95 -1.164057  1.079703
96  1.345990 -0.338182
97  0.699204 -1.261378
98  0.057885 -0.900014
99  0.503968  0.597121

[100 rows x 2 columns]

In [15]:
data = {
	'Escola': ['A', 'B', 'A', 'B', 'A' , 'B' , 'A', 'B'],
	'Student ID': [1001, 1002, 1003, 1004, 1005, 1006,
	1007, 1008],
	'Matematica': np.random.randint(60,100,8),
	'Ingles': np.random.randint(60,100,8),
	'Historia': np.random.randint(60,100,8)
	}

In [16]:
df2 = pd.DataFrame(data)

In [17]:
df2

  Escola  Student ID  Matematica  Ingles  Historia
0      A        1001          86      73        75
1      B        1002          99      77        84
2      A        1003          97      71        81
3      B        1004          77      82        90
4      A        1005          96      74        81
5      B        1006          82      99        64
6      A        1007          80      73        72
7      B        1008          77      72        64

In [18]:
df2[df2['Matematica']>75] # condicional

  Escola  Student ID  Matematica  Ingles  Historia
0      A        1001          86      73        75
1      B        1002          99      77        84
2      A        1003          97      71        81
3      B        1004          77      82        90
4      A        1005          96      74        81
5      B        1006          82      99        64
6      A        1007          80      73        72
7      B        1008          77      72        64

In [19]:
df2.loc[5:10,['Matematica','Ingles']] # fatiamento de coluna

   Matematica  Ingles
5          82      99
6          80      73
7          77      72

In [20]:
df2.loc[(df2['Matematica']>75) | (df2['Ingles'] < 60), ['Matematica','Ingles']] # fatiamento com operador logico

   Matematica  Ingles
0          86      73
1          99      77
2          97      71
3          77      82
4          96      74
5          82      99
6          80      73
7          77      72

In [23]:
df2['total'] = df2['Matematica'] + df2['Ingles'] + df2['Historia']

In [24]:
df2

  Escola  Student ID  Matematica  Ingles  Historia  total
0      A        1001          86      73        75    234
1      B        1002          99      77        84    260
2      A        1003          97      71        81    249
3      B        1004          77      82        90    249
4      A        1005          96      74        81    251
5      B        1006          82      99        64    245
6      A        1007          80      73        72    225
7      B        1008          77      72        64    213