<a href="https://colab.research.google.com/github/lucasat2/Jornada_python/blob/main/introducao_pandas/Serie_temporal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [25]:
# Crie um intervalo de datas para um ano
dates_rng= pd.date_range(start = '1/1/2018', end='12/31/2018', freq ='D')

In [26]:
# Gerando flutuações aleatórias em torno do preço inicial da ação, base em 100 reais
stock_data = 100 + np.cumsum(np.random.randn(365)* 2)

In [27]:
# Criando um Dataframe
df = pd.DataFrame(stock_data, index=dates_rng, columns=['Preco'])

In [28]:
df

                 Preco
2018-01-01   99.847063
2018-01-02  100.149065
2018-01-03  101.669915
2018-01-04  103.280649
2018-01-05  100.272012
...                ...
2018-12-27   70.050533
2018-12-28   70.671677
2018-12-29   70.618466
2018-12-30   68.389671
2018-12-31   66.770560

[365 rows x 1 columns]

In [29]:
# Preço médio da ação por mes

mensal = df.resample('ME').mean()

In [30]:
mensal

                 Preco
2018-01-31   96.896948
2018-02-28   95.201651
2018-03-31   95.130850
2018-04-30   94.155294
2018-05-31   85.905753
2018-06-30   89.721422
2018-07-31   95.578773
2018-08-31  101.376422
2018-09-30   98.205704
2018-10-31   87.098021
2018-11-30   83.861784
2018-12-31   71.864442

In [33]:
# preço no dia seguinte

#criando uma nova coluna com o preço deslocado de 1 dia

df['Preco_dia_seguinte'] = df['Preco'].shift(1)

#variacao diaria do preço
df['Mudanca diaria'] = df['Preco'] - df['Preco_dia_seguinte']

In [34]:
df

                 Preco  Preco_dia_seguinte  Mudanca diaria
2018-01-01   99.847063                 NaN             NaN
2018-01-02  100.149065           99.847063        0.302002
2018-01-03  101.669915          100.149065        1.520850
2018-01-04  103.280649          101.669915        1.610734
2018-01-05  100.272012          103.280649       -3.008637
...                ...                 ...             ...
2018-12-27   70.050533           69.207587        0.842946
2018-12-28   70.671677           70.050533        0.621145
2018-12-29   70.618466           70.671677       -0.053211
2018-12-30   68.389671           70.618466       -2.228795
2018-12-31   66.770560           68.389671       -1.619111

[365 rows x 3 columns]

In [35]:
# Janelas Rolantes - Ajudam a observar a tendencia em um tempo

# Calcular a media movel em 7 dias.

df_rolling = df.rolling(7).mean()


# os 7 primeiros valores darao nulo pois ainda nao temos dados anteriores

In [37]:
df_rolling

                Preco  Preco_dia_seguinte  Mudanca diaria
2018-01-01        NaN                 NaN             NaN
2018-01-02        NaN                 NaN             NaN
2018-01-03        NaN                 NaN             NaN
2018-01-04        NaN                 NaN             NaN
2018-01-05        NaN                 NaN             NaN
...               ...                 ...             ...
2018-12-27  66.926187           65.949268        0.976920
2018-12-28  67.657557           66.926187        0.731370
2018-12-29  68.468839           67.657557        0.811282
2018-12-30  68.856718           68.468839        0.387879
2018-12-31  69.084570           68.856718        0.227852

[365 rows x 3 columns]