<a href="https://colab.research.google.com/github/lucasat2/Jornada_python/blob/main/introducao_pandas/Mesclagem_de_dfs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
import numpy as np


data = {
	'Escola': ['A', 'B', 'A', 'B', 'A' , 'B' , 'A', 'B'],
	'Student ID': [1001, 1002, 1003, 1004, 1005, 1006,1007, 1008],
	'Matematica': np.random.randint(60,100,8),
	'Ingles': np.random.randint(60,100,8),
	'Historia': np.random.randint(60,100,8)
	}

In [14]:
df = pd.DataFrame(data)

In [10]:
# Alteramos os 2 ultimos IDS de proposito

sports_data = {
  'Student ID': [1001, 1002, 1003, 1004, 1005,
  1006, 1009, 1010],
  'Esportes': ['Futebol', 'Basquete', 'Volei', 'Futebol','Volei', 'Futebol', 'Basquete','Volei'
]}

In [11]:
sports_df = pd.DataFrame(sports_data)

In [6]:
sports_df

   Student ID  Esportes
0        1001   Futebol
1        1002  Basquete
2        1003     Volei
3        1004   Futebol
4        1005     Volei
5        1006   Futebol
6        1009  Basquete
7        1010     Volei

In [15]:
pd.merge(df, sports_df, on='Student ID')

  Escola  Student ID  Matematica  Ingles  Historia  Esportes
0      A        1001          96      65        66   Futebol
1      B        1002          64      89        80  Basquete
2      A        1003          75      95        70     Volei
3      B        1004          89      84        85   Futebol
4      A        1005          63      99        64     Volei
5      B        1006          77      75        69   Futebol

In [16]:
# Perceba que somente os ids comuns entre os 2 dfs foram mesclados

In [17]:
# Para unir os diferentes precisamos usar o que se segue abaixo

In [18]:
merged_outer = pd.merge(df, sports_df, on='Student ID', how='outer')

In [19]:
merged_outer

  Escola  Student ID  Matematica  Ingles  Historia  Esportes
0      A        1001        96.0    65.0      66.0   Futebol
1      B        1002        64.0    89.0      80.0  Basquete
2      A        1003        75.0    95.0      70.0     Volei
3      B        1004        89.0    84.0      85.0   Futebol
4      A        1005        63.0    99.0      64.0     Volei
5      B        1006        77.0    75.0      69.0   Futebol
6      A        1007        65.0    75.0      69.0       NaN
7      B        1008        83.0    70.0      61.0       NaN
8    NaN        1009         NaN     NaN       NaN  Basquete
9    NaN        1010         NaN     NaN       NaN     Volei

In [20]:
# Concatenar dataframes

In [21]:
data2 = {
	'Escola': ['A', 'B', 'A', 'B', 'A' , 'B' , 'A', 'B'],
	'Student ID': [1009,1010,1011,1012,1013,1014,1015,1016],
	'Matematica': np.random.randint(60,100,8),
	'Ingles': np.random.randint(60,100,8),
	'Historia': np.random.randint(60,100,8)
	}

df2 = pd.DataFrame(data2)

In [22]:
concatenado = pd.concat([df,df2], ignore_index=True)

In [23]:
concatenado

   Escola  Student ID  Matematica  Ingles  Historia
0       A        1001          96      65        66
1       B        1002          64      89        80
2       A        1003          75      95        70
3       B        1004          89      84        85
4       A        1005          63      99        64
5       B        1006          77      75        69
6       A        1007          65      75        69
7       B        1008          83      70        61
8       A        1009          65      73        72
9       B        1010          69      72        62
10      A        1011          91      80        69
11      B        1012          62      84        90
12      A        1013          79      93        62
13      B        1014          92      82        88
14      A        1015          83      85        96
15      B        1016          64      71        92

* A MESCLAGEM É USADA QUANDO QUEREMOS ADICIONAR DADOS A UMA NOVA COLUNA E O CONCAT É QUANDO
TEMOS UM DATAFRAME COM A MESMA ESTRUTURA E QUEREMOS APENAS ADICIONAR MAIS DADOS AO FINAL.