In [ ]:
import requests
import pandas as pd
from pandas import json_normalize



url = "https://jsonplaceholder.typicode.com/users"

#Puxando os dados da url
resposta = requests.get(url)

resposta.raise_for_status()

#Converter o resultado da url em json
dados = resposta.json()  

# Achata o JSON
df = json_normalize(dados)


print("Colunas disponíveis:")
print(df.columns)


# Vamos escolher algumas colunas
colunas_interesse = [
    "id",
    "name",
    "email",
    "address.city",
    "address.street",
    "company.name"
]

df_simplificado = df[colunas_interesse].rename(
    columns={
        "name": "nome",
        "address.city": "cidade",
        "address.street": "rua",
        "company.name": "empresa"
    }
)

print("\nDataFrame simplificado:")
print(df_simplificado.head())
print("\nInfo:")
print(df_simplificado.info())

# Exercicios

In [2]:
produtos = [
    {"id": 1, "nome": "Teclado Mecânico", "preco": 250.0, "estoque": 10},
    {"id": 2, "nome": "Mouse Gamer",      "preco": 150.0, "estoque": 0},
    {"id": 3, "nome": "Monitor 24\"",     "preco": 900.0, "estoque": 5},
    {"id": 4, "nome": "Cadeira Gamer",    "preco": 1200.0, "estoque": 2}
]

Tarefas:

Crie um DataFrame df_produtos a partir dessa lista.

Use df_produtos.head() e df_produtos.info() para explorar.

Crie uma nova coluna em_estoque que recebe:

"Sim" se estoque > 0

"Não" caso contrário

Calcule o preço médio dos produtos (preco).

In [3]:
df_produtos = pd.DataFrame(produtos)

In [4]:
df_produtos.head()

   id              nome   preco  estoque
0   1  Teclado Mecânico   250.0       10
1   2       Mouse Gamer   150.0        0
2   3       Monitor 24"   900.0        5
3   4     Cadeira Gamer  1200.0        2

In [5]:
df_produtos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       4 non-null      int64
 1   nome     4 non-null      object
 2   preco    4 non-null      float64
 3   estoque  4 non-null      int64
dtypes: float64(1), int64(2), object(1)
memory usage: 260.0+ bytes

In [7]:
import numpy as np

df_produtos['em_estoque'] = np.where(df_produtos['estoque'] > 0, "Sim", "Não")
df_produtos

   id              nome   preco  estoque em_estoque
0   1  Teclado Mecânico   250.0       10        Sim
1   2       Mouse Gamer   150.0        0        Não
2   3       Monitor 24"   900.0        5        Sim
3   4     Cadeira Gamer  1200.0        2        Sim

In [10]:
media = df_produtos['preco'].mean()
print(media)

625.0